### PR TITLE
[EMAIL] Improve email sending reliability and security

### LINKED ISSUE #280: Email not working
Using Power Automate to generate a secret, everything says successful and I see the secrets created on my account, however the email isn't sent.  I have tried multiple emails and never received any.

### PR DESCRIPTION
**Pull request by delano**
## **User description**
This pull request fixes the issue where emails are not being sent. It includes several improvements to the email functionality, such as wrapping URLs in email templates with HTML <a> tags to make them clickable, improving log handling, fixing the reset password request logic, and addressing the email from address. These changes should ensure that emails are sent successfully and improve the overall email functionality.

Fixes #280, #285

___

## **Type**
Bug fix

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Error handling
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>base.rb</strong><dd><code>Improve error handling and logging in API</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

lib/onetime/app/api/base.rb
<li>Removed verbose debug logging of locale information<br> <li> Improved error handling for rate limiting exceptions<br>

</details>

  </td>
  <td><a href="https://github.com/onetimesecret/onetimesecret/pull/307/files#diff-d373c9db90dbcb4a66720f177566ef4757dcce10a3b3e79ba7df31e1f82b86c7">+0/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>

<tr>
  <td>
    <details>
      <summary><strong>helpers.rb</strong><dd><code>Enhance rate limiting error handling and logging</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

lib/onetime/app/helpers.rb
<li>Obscured customer identifiers in rate limiting logs using a hashing <br>function<br> <li> Replaced verbose debug logging with targeted error handling<br> <li> Improved error messages for rate limiting exceptions<br>

</details>

  </td>
  <td><a href="https://github.com/onetimesecret/onetimesecret/pull/307/files#diff-e94d14dd7ae26375167811c7ec80077c552df686cbd9b62877e36f299e28725a">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
</table></td></tr>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by onetimesecret** [comment]
**[PR Description](https://github.com/onetimesecret/onetimesecret/pull/307)** updated to latest commit (https://github.com/onetimesecret/onetimesecret/commit/0b514bca630f93b5033df75cd6118c9c6f9ed4f9)

**Comment by onetimesecret** [comment]
## PR Review

<table>
<tr>
<tr><td> ⏱️&nbsp;<strong>Estimated&nbsp;effort&nbsp;to&nbsp;review [1-5]</strong></td><td>

3, because the PR includes several changes across multiple files, including error handling, logging, email sending, and email template updates. The changes seem focused on improving the reliability and security of the email functionality, which is an important part of the application.


</td></tr>
<tr><td> 🧪&nbsp;<strong>Relevant tests</strong></td><td>

No


</td></tr>
<tr><td> 🔍&nbsp;<strong>Possible issues</strong></td><td>

No

</td></tr>
<tr><td> 🔒&nbsp;<strong>Security concerns</strong></td><td>

No

</td></tr>
</table>

File: lib/onetime/app/api/base.rb [hunk 1]
```diff
@@ -63,7 +63,6 @@ def check_locale! locale=nil
         locales << OT.conf[:locales].first                              # Ensure at least one configured locale is available
         locales = locales.uniq.reject { |l| !OT.locales.has_key?(l) }.compact
         locale = locales.first if !OT.locales.has_key?(locale)           # Default to the first available
-        OT.ld [:locale, locale, locales, req.env['rack.locale'], OT.locales.keys].inspect
         req.env['ots.locale'], req.env['ots.locales'] = (@locale = locale), locales
```
Comment (onetimesecret) [inline lib/onetime/app/api/base.rb:70]: Consider adding a comment or docstring to explain the purpose of the `check_locale!` method and how it works. This will make the code more self-documenting and easier for other developers to understand. [medium]

Comment (delano) [reply lib/onetime/app/api/base.rb:70]: There already were docs for it so I pushed an update anyway for clarity. 🙏
